from __future__ import annotations

import hashlib
import json
import textwrap

from metaharness.sdk.api import HarnessAPI
from metaharness.sdk.base import HarnessComponent
from metaharness.sdk.runtime import ComponentRuntime
from metaharness_ext.fealpy.capabilities import CAP_FEALPY_COMPILE
from metaharness_ext.fealpy.contracts import (
    FealpyEnvironmentReport,
    FealpyProblemSpec,
    FealpyRunPlan,
)
from metaharness_ext.fealpy.slots import FEALPY_COMPILER_SLOT

_FAMILY_RENDERERS: dict[str, str] = {
    # Tier 1 — scalar diffusion (Lagrange + ScalarDiffusionIntegrator)
    "poisson": "_render_scalar_diffusion",
    "diffusion_convection_reaction": "_render_scalar_diffusion",
    "diffusion_reaction": "_render_scalar_diffusion",
    "hyperbolic": "_render_scalar_diffusion",
    "parabolic": "_render_scalar_diffusion",
    "wave": "_render_scalar_diffusion",
    "interface_poisson": "_render_scalar_diffusion",
    "polyharmonic": "_render_scalar_diffusion",
    "quasilinear_elliptic": "_render_scalar_diffusion",
    "mgtensor_possion": "_render_scalar_diffusion",
    "helmholtz": "_render_scalar_diffusion",
    "surface_poisson": "_render_scalar_diffusion",
    # Tier 2 — vector / mixed problems
    "curlcurl": "_render_curl_curl",
    "linear_elasticity": "_render_linear_elasticity",
    "darcy": "_render_darcy",
    "darcyforchheimer": "_render_darcy",
    "stokes": "_render_stokes",
    # Tier 3 — transient / nonlinear
    "allen_cahn": "_render_allen_cahn",
    "navier_stokes": "_render_navier_stokes",
}


class FealpyCompilerComponent(HarnessComponent):
    async def activate(self, runtime: ComponentRuntime) -> None:
        self._runtime = runtime

    async def deactivate(self) -> None:
        self._runtime = None

    def declare_interface(self, api: HarnessAPI) -> None:
        api.bind_slot(FEALPY_COMPILER_SLOT)
        api.declare_input("task", "FealpyProblemSpec")
        api.declare_input("environment", "FealpyEnvironmentReport", required=False)
        api.declare_output("plan", "FealpyRunPlan", mode="sync")
        api.provide_capability(CAP_FEALPY_COMPILE)

    def compile(
        self,
        spec: FealpyProblemSpec,
        environment: FealpyEnvironmentReport | None = None,
    ) -> FealpyRunPlan:
        if environment is not None and not environment.available:
            raise ValueError(f"fealpy environment unavailable: {environment.status}")

        plan_id = self._build_plan_id(spec)
        run_id = f"run-{plan_id}"
        workspace_dir = f".runs/fealpy/{spec.task_id}/{run_id}"
        script_source = self._render_script(spec, plan_id)

        return FealpyRunPlan(
            plan_id=plan_id,
            task_id=spec.task_id,
            run_id=run_id,
            spec=spec,
            workspace_dir=workspace_dir,
            script_source=script_source,
            graph_metadata=dict(spec.graph_metadata),
            promotion_metadata=dict(spec.promotion_metadata),
            evidence_refs=[f"fealpy://plan/{spec.task_id}/{plan_id}"],
        )

    def _build_plan_id(self, spec: FealpyProblemSpec) -> str:
        payload = json.dumps(spec.model_dump(mode="json"), sort_keys=True)
        digest = hashlib.sha256(payload.encode()).hexdigest()[:12]
        return f"fealpy-{spec.task_id}-{digest}"

    # ── dispatch ──────────────────────────────────────────────────────────

    def _render_script(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        renderer_name = _FAMILY_RENDERERS.get(spec.pde_family, "_render_scalar_diffusion")
        renderer = getattr(self, renderer_name)
        return renderer(spec, plan_id)

    # ── shared template fragments ─────────────────────────────────────────

    def _render_header(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        return textwrap.dedent(f"""\
        # Auto-generated by metaharness_ext.fealpy
        # Plan: {plan_id}  Task: {spec.task_id}  PDE: {spec.pde_family}
        import json
        import sys
        import time

        from fealpy.backend import backend_manager as bm

        bm.set_backend('{spec.backend}')

        from fealpy.fem import BilinearForm, LinearForm, DirichletBC
        from fealpy.functionspace import LagrangeFESpace
        from fealpy.model import PDEModelManager
        from fealpy.solver import spsolve
        """)

    def _render_mesh_builder(self) -> str:
        return textwrap.dedent("""\

        def _build_mesh(pde, mesh_spec):
            meshtype = mesh_spec.get("meshtype", "tri")
            nx = mesh_spec.get("nx", 8)
            ny = mesh_spec.get("ny")
            nz = mesh_spec.get("nz")
            domain = list(pde.domain()) if hasattr(pde, 'domain') else [0, 1]
            if meshtype == "interval":
                from fealpy.mesh import IntervalMesh
                return IntervalMesh.from_interval(domain, nx=nx)
            elif meshtype == "uniform":
                gdim = pde.geo_dimension() if hasattr(pde, 'geo_dimension') else 2
                if gdim == 1:
                    from fealpy.mesh import UniformMesh1d
                    return UniformMesh1d.from_interval(domain, nx=nx)
                elif gdim == 2:
                    from fealpy.mesh import UniformMesh2d
                    return UniformMesh2d.from_box(
                        [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                    )
                else:
                    from fealpy.mesh import UniformMesh3d
                    return UniformMesh3d.from_box(
                        [domain[0], domain[1], domain[0], domain[1], domain[0], domain[1]],
                        nx=nx, ny=ny or nx, nz=nz or nx,
                    )
            elif meshtype == "quad":
                from fealpy.mesh import QuadrangleMesh
                return QuadrangleMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                )
            elif meshtype == "tet":
                from fealpy.mesh import TetrahedronMesh
                return TetrahedronMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1], domain[0], domain[1]],
                    nx=nx, ny=ny or nx, nz=nz or nx,
                )
            elif meshtype == "hex":
                from fealpy.mesh import HexahedronMesh
                return HexahedronMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1], domain[0], domain[1]],
                    nx=nx, ny=ny or nx, nz=nz or nx,
                )
            else:
                from fealpy.mesh import TriangleMesh
                return TriangleMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                )
        """)

    def _render_pde_load(self, spec: FealpyProblemSpec) -> str:
        return textwrap.dedent(f"""\

        try:
            pde = PDEModelManager('{spec.pde_family}').get_example({spec.example_key})
        except Exception as exc:
            print(json.dumps({{"status": "failed", "error": f"PDE load: {{exc}}"}}))
            sys.exit(1)

        mesh_spec = json.loads('{json.dumps(spec.mesh.model_dump(mode="json"))}')
        mesh = _build_mesh(pde, mesh_spec)
        nc = mesh.number_of_cells()
        nn = mesh.number_of_nodes()

        t0 = time.perf_counter()
        """)

    def _render_scalar_output(self, spec: FealpyProblemSpec) -> str:
        return textwrap.dedent(f"""\

        uh = spsolve(A, F, solver='{spec.solver.method}')
        uh_func = space.function()
        uh_func[:] = uh
        wall = time.perf_counter() - t0

        l2 = float(mesh.error(pde.solution, uh_func))
        if hasattr(pde, 'gradient'):
            h1 = float(mesh.error(pde.gradient, uh_func.grad_value))
        else:
            h1 = None

        result = {{
            "status": "completed",
            "l2_error": l2,
            "h1_error": h1,
            "dof": space.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)

    # ── Tier 1: scalar diffusion ──────────────────────────────────────────

    def _render_scalar_diffusion(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        header = self._render_header(spec, plan_id)
        # Add scalar-specific imports
        header = header.replace(
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC",
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC\n"
            "from fealpy.fem import ScalarDiffusionIntegrator, ScalarSourceIntegrator",
        )
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent(f"""\

        # -- FE space (scalar Lagrange) -------------------------------------
        space = LagrangeFESpace(mesh, p={spec.fe_degree})

        # -- Assembly --------------------------------------------------------
        bform = BilinearForm(space)
        bform.add_integrator(ScalarDiffusionIntegrator())
        lform = LinearForm(space)
        lform.add_integrator(ScalarSourceIntegrator(pde.source))
        A = bform.assembly()
        F = lform.assembly()

        # -- Boundary conditions ---------------------------------------------
        if hasattr(pde, 'dirichlet'):
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        elif hasattr(pde, 'robin'):
            A, F = DirichletBC(space, gd=pde.solution,
                threshold=pde.is_robin_boundary).apply(A, F)
        elif hasattr(pde, 'neumann'):
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        else:
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        """)
        output = self._render_scalar_output(spec)
        return header + mesh_builder + pde_load + assembly + output

    # ── Tier 2: curl-curl (Nedelec) ───────────────────────────────────────

    def _render_curl_curl(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        header = self._render_header(spec, plan_id)
        header = header.replace(
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC",
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC\n"
            "from fealpy.fem import CurlCurlIntegrator, ScalarSourceIntegrator\n"
            "from fealpy.functionspace import FirstNedelecFESpace",
        )
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent(f"""\

        # -- FE space (Nedelec edge elements) -------------------------------
        space = FirstNedelecFESpace(mesh, p={spec.fe_degree})

        # -- Assembly --------------------------------------------------------
        bform = BilinearForm(space)
        bform.add_integrator(CurlCurlIntegrator())
        lform = LinearForm(space)
        lform.add_integrator(ScalarSourceIntegrator(pde.source))
        A = bform.assembly()
        F = lform.assembly()

        # -- Boundary conditions ---------------------------------------------
        if hasattr(pde, 'dirichlet'):
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        else:
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        """)
        output = self._render_scalar_output(spec)
        return header + mesh_builder + pde_load + assembly + output

    # ── Tier 2: linear elasticity (Hu-Zhang) ──────────────────────────────

    def _render_linear_elasticity(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        header = self._render_header(spec, plan_id)
        header = header.replace(
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC",
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC\n"
            "from fealpy.fem import LinearElasticityIntegrator, VectorSourceIntegrator\n"
            "from fealpy.functionspace import HuZhangFESpace\n"
            "from fealpy.material.elastic_material import ElasticMaterial",
        )
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent(f"""\

        # -- FE space (Hu-Zhang for linear elasticity) ----------------------
        space = HuZhangFESpace(mesh, p={spec.fe_degree})
        material = ElasticMaterial(name='lam')
        material.set_property('lame_lambda', 1.0)
        material.set_property('lame_mu', 1.0)

        # -- Assembly --------------------------------------------------------
        bform = BilinearForm(space)
        bform.add_integrator(LinearElasticityIntegrator(material=material, q={spec.fe_degree + 2}))
        lform = LinearForm(space)
        lform.add_integrator(VectorSourceIntegrator(pde.body_force))
        A = bform.assembly()
        F = lform.assembly()

        # -- Boundary conditions ---------------------------------------------
        if hasattr(pde, 'dirichlet'):
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        else:
            A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        """)
        output = self._render_scalar_output(spec)
        return header + mesh_builder + pde_load + assembly + output

    # ── Tier 2: Darcy (Raviart-Thomas mixed) ──────────────────────────────

    def _render_darcy(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        header = textwrap.dedent(f"""\
        # Auto-generated by metaharness_ext.fealpy
        # Plan: {plan_id}  Task: {spec.task_id}  PDE: {spec.pde_family}
        import json
        import sys
        import time

        from fealpy.backend import backend_manager as bm

        bm.set_backend('{spec.backend}')

        from fealpy.fem import (
            BilinearForm, LinearForm, DirichletBC,
            BlockForm, LinearBlockForm,
        )
        from fealpy.fem import DivIntegrator, ScalarMassIntegrator, ScalarSourceIntegrator
        from fealpy.functionspace import LagrangeFESpace, RaviartThomasFESpace
        from fealpy.model import PDEModelManager
        from fealpy.solver import spsolve
        """)
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent("""\

        # -- Mixed FE spaces (RT flux + P0 pressure) ------------------------
        uspace = RaviartThomasFESpace(mesh, p=0)
        pspace = LagrangeFESpace(mesh, p=0)

        # -- Assembly: block saddle-point system -----------------------------
        bform_M = BilinearForm(uspace)
        bform_M.add_integrator(ScalarMassIntegrator(coef=1.0, q=3))
        bform_B = BilinearForm((pspace, uspace))
        bform_B.add_integrator(DivIntegrator(coef=-1, q=3))

        M = BlockForm([[bform_M, bform_B.T],
                       [bform_B, None]])
        A = M.assembly()

        lform_F = LinearForm(uspace)
        lform_F.add_integrator(ScalarSourceIntegrator(pde.source))
        lform_G = LinearForm(pspace)
        F = LinearBlockForm([lform_F, lform_G]).assembly()

        # -- Boundary conditions ---------------------------------------------
        if hasattr(pde, 'dirichlet'):
            A, F = DirichletBC(uspace, gd=pde.solution).apply(A, F)
        """)
        output = textwrap.dedent(f"""\

        uh = spsolve(A, F, solver='{spec.solver.method}')
        uh_func = uspace.function()
        uh_func[:] = uh
        wall = time.perf_counter() - t0

        result = {{
            "status": "completed",
            "l2_error": None,
            "h1_error": None,
            "dof": uspace.number_of_global_dofs() + pspace.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)
        return header + mesh_builder + pde_load + assembly + output

    # ── Tier 3: transient + nonlinear ────────────────────────────────────

    def _render_allen_cahn(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        dt = spec.dt
        n_steps = spec.num_time_steps
        header = self._render_header(spec, plan_id)
        header = header.replace(
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC",
            "from fealpy.fem import BilinearForm, LinearForm, DirichletBC\n"
            "from fealpy.fem import ScalarDiffusionIntegrator, ScalarMassIntegrator, "
            "ScalarSourceIntegrator",
        )
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent(f"""\

        # -- FE space (scalar Lagrange) -------------------------------------
        space = LagrangeFESpace(mesh, p={spec.fe_degree})
        epsilon = getattr(pde, 'epsilon', 0.01)

        # -- Mass & stiffness matrices --------------------------------------
        bform_m = BilinearForm(space)
        bform_m.add_integrator(ScalarMassIntegrator(coef=1.0, q={spec.fe_degree + 2}))
        M = bform_m.assembly()

        bform_a = BilinearForm(space)
        bform_a.add_integrator(ScalarDiffusionIntegrator(coef=epsilon, q={spec.fe_degree + 2}))
        A_stiff = bform_a.assembly()

        # -- Initial condition from PDE or zero ------------------------------
        if hasattr(pde, 'solution'):
            u = space.interpolate(pde.solution)
        else:
            u = space.function()
            u[:] = 0.0

        uh_func = space.function()

        # -- Time loop (semi-implicit convex splitting) ----------------------
        dt_inv = 1.0 / {dt}
        A_lhs = dt_inv * M + A_stiff

        for step in range({n_steps}):
            # Nonlinear double-well force: W'(u) = u^3 - u (explicit)
            u_nl = space.function()
            u_nl[:] = u[:] ** 3 - u[:]
            lform_nl = LinearForm(space)
            lform_nl.add_integrator(ScalarSourceIntegrator(u_nl))

            lform = LinearForm(space)
            if hasattr(pde, 'source'):
                lform.add_integrator(ScalarSourceIntegrator(pde.source))

            F_rhs = dt_inv * M @ u - lform_nl.assembly() + lform.assembly()

            A_lhs_bc, F_rhs_bc = A_lhs.copy(), F_rhs.copy()
            if hasattr(pde, 'dirichlet'):
                A_lhs_bc, F_rhs_bc = DirichletBC(space, gd=pde.solution).apply(
                    A_lhs_bc, F_rhs_bc)
            else:
                A_lhs_bc, F_rhs_bc = DirichletBC(space, gd=pde.solution).apply(
                    A_lhs_bc, F_rhs_bc)

            u_new = spsolve(A_lhs_bc, F_rhs_bc, solver='{spec.solver.method}')
            u[:] = u_new[:]

        uh_func[:] = u[:]
        wall = time.perf_counter() - t0

        l2 = float(mesh.error(pde.solution, uh_func)) if hasattr(pde, 'solution') else None
        h1 = (
            float(mesh.error(pde.gradient, uh_func.grad_value))
            if hasattr(pde, 'gradient') else None
        )

        result = {{
            "status": "completed",
            "l2_error": l2,
            "h1_error": h1,
            "dof": space.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "num_time_steps": {n_steps},
            "dt": {dt},
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)
        return header + mesh_builder + pde_load + assembly

    def _render_navier_stokes(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        dt = spec.dt
        n_steps = spec.num_time_steps
        header = textwrap.dedent(f"""\
        # Auto-generated by metaharness_ext.fealpy
        # Plan: {plan_id}  Task: {spec.task_id}  PDE: {spec.pde_family}
        import json
        import sys
        import time

        from fealpy.backend import backend_manager as bm

        bm.set_backend('{spec.backend}')

        from fealpy.fem import (
            BilinearForm, LinearForm, DirichletBC,
            BlockForm, LinearBlockForm,
        )
        from fealpy.fem import (
            DivIntegrator,
            ScalarMassIntegrator,
            ScalarSourceIntegrator,
            ViscousWorkIntegrator,
        )
        from fealpy.functionspace import LagrangeFESpace
        from fealpy.model import PDEModelManager
        from fealpy.solver import spsolve
        """)
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent(f"""\

        # -- Taylor-Hood mixed spaces ---------------------------------------
        velocity_space = LagrangeFESpace(mesh, p=2)
        pressure_space = LagrangeFESpace(mesh, p=1)

        nu = getattr(pde, 'viscosity', 1.0)
        max_picard_iters = 10
        picard_rtol = 1e-6

        if hasattr(pde, 'solution'):
            u = velocity_space.interpolate(pde.solution)
        else:
            u = velocity_space.function()
            u[:] = 0.0

        wall = time.perf_counter() - t0

        # -- Time loop with Picard iteration --------------------------------
        dt_inv = 1.0 / {dt}

        for step in range({n_steps}):
            u_prev = velocity_space.function()
            u_prev[:] = u[:]

            for picard_iter in range(max_picard_iters):
                bform_A = BilinearForm(velocity_space)
                bform_A.add_integrator(ViscousWorkIntegrator(coef=nu, q=3))
                bform_m = BilinearForm(velocity_space)
                bform_m.add_integrator(ScalarMassIntegrator(coef=dt_inv, q=3))
                A_mat = bform_A.assembly() + bform_m.assembly()

                bform_B = BilinearForm((pressure_space, velocity_space))
                bform_B.add_integrator(DivIntegrator(coef=1, q=3))

                bform_C = BilinearForm(pressure_space)
                eps_stab = 1e-10
                bform_C.add_integrator(ScalarMassIntegrator(coef=eps_stab, q=3))

                M_block = BlockForm([[A_mat, bform_B.T],
                                     [bform_B, bform_C]])
                A = M_block.assembly()

                lform_F = LinearForm(velocity_space)
                if hasattr(pde, 'source'):
                    lform_F.add_integrator(ScalarSourceIntegrator(pde.source))
                lform_G = LinearForm(pressure_space)
                F = LinearBlockForm([lform_F, lform_G]).assembly()

                if hasattr(pde, 'dirichlet'):
                    A, F = DirichletBC(velocity_space, gd=pde.solution).apply(A, F)
                else:
                    A, F = DirichletBC(velocity_space, gd=pde.solution).apply(A, F)

                uh = spsolve(A, F, solver='{spec.solver.method}')
                u_new = velocity_space.function()
                u_new[:] = uh[:velocity_space.number_of_global_dofs()]

                diff = velocity_space.function()
                diff[:] = u_new[:] - u[:]
                norm_u0 = max(float((u_prev[:] ** 2).sum()) ** 0.5, 1e-12)
                norm_diff = float((diff[:] ** 2).sum()) ** 0.5
                u[:] = u_new[:]
                if norm_diff < picard_rtol * norm_u0:
                    break

        uh_func = velocity_space.function()
        uh_func[:] = u[:]
        wall = time.perf_counter() - t0

        result = {{
            "status": "completed",
            "l2_error": None,
            "h1_error": None,
            "dof": velocity_space.number_of_global_dofs()
                   + pressure_space.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "num_time_steps": {n_steps},
            "dt": {dt},
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)
        return header + mesh_builder + pde_load + assembly

    # ── Tier 2: Stokes (Taylor-Hood mixed) ────────────────────────────────

    def _render_stokes(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        header = textwrap.dedent(f"""\
        # Auto-generated by metaharness_ext.fealpy
        # Plan: {plan_id}  Task: {spec.task_id}  PDE: {spec.pde_family}
        import json
        import sys
        import time

        from fealpy.backend import backend_manager as bm

        bm.set_backend('{spec.backend}')

        from fealpy.fem import (
            BilinearForm, LinearForm, DirichletBC,
            BlockForm, LinearBlockForm,
        )
        from fealpy.fem import (
            DivIntegrator,
            ScalarMassIntegrator,
            ScalarSourceIntegrator,
            ViscousWorkIntegrator,
        )
        from fealpy.functionspace import LagrangeFESpace
        from fealpy.model import PDEModelManager
        from fealpy.solver import spsolve
        """)
        mesh_builder = self._render_mesh_builder()
        pde_load = self._render_pde_load(spec)
        assembly = textwrap.dedent("""\

        # -- Taylor-Hood mixed spaces (P2 velocity + P1 pressure) -----------
        velocity_space = LagrangeFESpace(mesh, p=2)
        pressure_space = LagrangeFESpace(mesh, p=1)

        # -- Assembly: block saddle-point system -----------------------------
        bform_A = BilinearForm(velocity_space)
        bform_A.add_integrator(ViscousWorkIntegrator())
        bform_B = BilinearForm((pressure_space, velocity_space))
        bform_B.add_integrator(DivIntegrator(coef=1, q=3))
        bform_C = BilinearForm(pressure_space)
        eps = 1e-10
        bform_C.add_integrator(ScalarMassIntegrator(coef=eps, q=3))

        M = BlockForm([[bform_A, bform_B.T],
                       [bform_B, bform_C]])
        A = M.assembly()

        lform_F = LinearForm(velocity_space)
        lform_F.add_integrator(ScalarSourceIntegrator(pde.source))
        lform_G = LinearForm(pressure_space)
        F = LinearBlockForm([lform_F, lform_G]).assembly()

        # -- Boundary conditions ---------------------------------------------
        if hasattr(pde, 'dirichlet'):
            A, F = DirichletBC(velocity_space, gd=pde.solution).apply(A, F)
        """)
        output = textwrap.dedent(f"""\

        uh = spsolve(A, F, solver='{spec.solver.method}')
        uh_func = velocity_space.function()
        uh_func[:] = uh
        wall = time.perf_counter() - t0

        result = {{
            "status": "completed",
            "l2_error": None,
            "h1_error": None,
            "dof": velocity_space.number_of_global_dofs()
                   + pressure_space.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)
        return header + mesh_builder + pde_load + assembly + output
