from __future__ import annotations

import hashlib
import json
import textwrap

from metaharness.sdk.api import HarnessAPI
from metaharness.sdk.base import HarnessComponent
from metaharness.sdk.runtime import ComponentRuntime
from metaharness_ext.fealpy.capabilities import CAP_FEALPY_COMPILE
from metaharness_ext.fealpy.contracts import (
    FealpyEnvironmentReport,
    FealpyProblemSpec,
    FealpyRunPlan,
)
from metaharness_ext.fealpy.slots import FEALPY_COMPILER_SLOT


class FealpyCompilerComponent(HarnessComponent):
    async def activate(self, runtime: ComponentRuntime) -> None:
        self._runtime = runtime

    async def deactivate(self) -> None:
        self._runtime = None

    def declare_interface(self, api: HarnessAPI) -> None:
        api.bind_slot(FEALPY_COMPILER_SLOT)
        api.declare_input("task", "FealpyProblemSpec")
        api.declare_input("environment", "FealpyEnvironmentReport", required=False)
        api.declare_output("plan", "FealpyRunPlan", mode="sync")
        api.provide_capability(CAP_FEALPY_COMPILE)

    def compile(
        self,
        spec: FealpyProblemSpec,
        environment: FealpyEnvironmentReport | None = None,
    ) -> FealpyRunPlan:
        if environment is not None and not environment.available:
            raise ValueError(f"fealpy environment unavailable: {environment.status}")

        plan_id = self._build_plan_id(spec)
        run_id = f"run-{plan_id}"
        workspace_dir = f".runs/fealpy/{spec.task_id}/{run_id}"
        script_source = self._render_script(spec, plan_id)

        return FealpyRunPlan(
            plan_id=plan_id,
            task_id=spec.task_id,
            run_id=run_id,
            spec=spec,
            workspace_dir=workspace_dir,
            script_source=script_source,
            graph_metadata=dict(spec.graph_metadata),
            promotion_metadata=dict(spec.promotion_metadata),
            evidence_refs=[f"fealpy://plan/{spec.task_id}/{plan_id}"],
        )

    def _build_plan_id(self, spec: FealpyProblemSpec) -> str:
        payload = json.dumps(spec.model_dump(mode="json"), sort_keys=True)
        digest = hashlib.sha256(payload.encode()).hexdigest()[:12]
        return f"fealpy-{spec.task_id}-{digest}"

    def _render_script(self, spec: FealpyProblemSpec, plan_id: str) -> str:
        mesh = spec.mesh
        return textwrap.dedent(f"""\
        # Auto-generated by metaharness_ext.fealpy
        # Plan: {plan_id}  Task: {spec.task_id}
        import json
        import sys
        import time

        from fealpy.backend import backend_manager as bm

        bm.set_backend('{spec.backend}')

        from fealpy.fem import BilinearForm, LinearForm, DirichletBC
        from fealpy.fem import ScalarDiffusionIntegrator, ScalarSourceIntegrator
        from fealpy.functionspace import LagrangeFESpace
        from fealpy.model import PDEModelManager
        from fealpy.solver import spsolve


        def _build_mesh(pde, mesh_spec):
            meshtype = mesh_spec.get("meshtype", "tri")
            nx = mesh_spec.get("nx", 8)
            ny = mesh_spec.get("ny")
            nz = mesh_spec.get("nz")
            domain = list(pde.domain()) if hasattr(pde, 'domain') else [0, 1]
            if meshtype == "interval":
                from fealpy.mesh import IntervalMesh
                return IntervalMesh.from_interval(domain, nx=nx)
            elif meshtype == "uniform":
                gdim = pde.geo_dimension() if hasattr(pde, 'geo_dimension') else 2
                if gdim == 1:
                    from fealpy.mesh import UniformMesh1d
                    return UniformMesh1d.from_interval(domain, nx=nx)
                elif gdim == 2:
                    from fealpy.mesh import UniformMesh2d
                    return UniformMesh2d.from_box(
                        [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                    )
                else:
                    from fealpy.mesh import UniformMesh3d
                    return UniformMesh3d.from_box(
                        [domain[0], domain[1], domain[0], domain[1], domain[0], domain[1]],
                        nx=nx, ny=ny or nx, nz=nz or nx,
                    )
            elif meshtype == "quad":
                from fealpy.mesh import QuadrangleMesh
                return QuadrangleMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                )
            else:
                from fealpy.mesh import TriangleMesh
                return TriangleMesh.from_box(
                    [domain[0], domain[1], domain[0], domain[1]], nx=nx, ny=ny or nx
                )


        try:
            pde = PDEModelManager('{spec.pde_family}').get_example({spec.example_key})
        except Exception as exc:
            print(json.dumps({{"status": "failed", "error": f"PDE load: {{exc}}"}}))
            sys.exit(1)

        mesh_spec = json.loads('{json.dumps(mesh.model_dump(mode="json"))}')
        mesh = _build_mesh(pde, mesh_spec)
        nc = mesh.number_of_cells()
        nn = mesh.number_of_nodes()

        t0 = time.perf_counter()
        space = LagrangeFESpace(mesh, p={spec.fe_degree})
        bform = BilinearForm(space)
        bform.add_integrator(ScalarDiffusionIntegrator())
        lform = LinearForm(space)
        lform.add_integrator(ScalarSourceIntegrator(pde.source))
        A = bform.assembly()
        F = lform.assembly()
        A, F = DirichletBC(space, gd=pde.solution).apply(A, F)
        uh = spsolve(A, F, solver='scipy')
        uh_func = space.function()
        uh_func[:] = uh
        wall = time.perf_counter() - t0

        l2 = float(mesh.error(pde.solution, uh_func))
        h1 = float(mesh.error(pde.gradient, uh_func.grad_value))

        result = {{
            "status": "completed",
            "l2_error": l2,
            "h1_error": h1,
            "dof": space.number_of_global_dofs(),
            "nc": nc,
            "nn": nn,
            "wall_time": round(wall, 4),
        }}
        print(json.dumps(result))
        """)
