"""Code generation pipeline for synthesised components.

Given a :class:`ComponentTemplate` and a set of slot bindings, produce
one or more generated artifacts: a manifest JSON, a Python stub for
the ``entry`` class, and optionally an XML fragment wiring the new
instance into a graph.
"""

from __future__ import annotations

import json
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from metaharness.optimizer.templates.registry import ComponentTemplate
from metaharness.optimizer.templates.slots import SlotBinding
from metaharness.sdk.manifest import ComponentManifest


@dataclass(slots=True)
class GeneratedArtifact:
    """One generated file with a suggested on-disk path."""

    path: Path
    content: str
    kind: str  # "manifest" | "module" | "graph_fragment"
    attributes: dict[str, Any] = field(default_factory=dict)


class CodegenPipeline:
    """Render generated artifacts from a template + bindings pair.

    Artifacts are kept in-memory; callers decide whether to flush them
    to disk via :meth:`write_all`. The pipeline is deterministic and
    does not execute generated code, so it stays safe to run inside the
    safety pipeline.
    """

    MODULE_TEMPLATE = textwrap.dedent(
        '''
        """Generated component stub for {template_id}.

        Auto-generated by CodegenPipeline. Do not hand-edit without
        adding a migration adapter entry.
        """

        from __future__ import annotations

        from metaharness.sdk.api import HarnessAPI
        from metaharness.sdk.base import HarnessComponent
        from metaharness.sdk.runtime import ComponentRuntime


        class {class_name}(HarnessComponent):
            """{description}"""

            async def activate(self, runtime: ComponentRuntime | None) -> None:
                self._runtime = runtime

            async def deactivate(self) -> None:
                self._runtime = None

            def declare_interface(self, api: HarnessAPI) -> None:
                api.bind_slot("{template_id}.primary")
        '''
    ).strip()

    GRAPH_FRAGMENT_TEMPLATE = textwrap.dedent(
        """
        <Component id="{component_id}" type="{component_type}" impl="{impl}" version="{version}" />
        """
    ).strip()

    def render(
        self,
        template: ComponentTemplate,
        manifest: ComponentManifest,
        bindings: list[SlotBinding],
        *,
        root: Path | None = None,
    ) -> list[GeneratedArtifact]:
        root = root or Path(".")
        artifacts: list[GeneratedArtifact] = []

        manifest_path = root / "manifests" / f"{manifest.resolved_id()}.json"
        manifest_content = json.dumps(manifest.model_dump(), indent=2, sort_keys=True)
        artifacts.append(
            GeneratedArtifact(
                path=manifest_path,
                content=manifest_content,
                kind="manifest",
                attributes={"bindings": {b.slot: b.value for b in bindings}},
            )
        )

        module_name = manifest.entry.split(":", 1)[0].replace(".", "/")
        module_path = root / "generated" / f"{module_name}.py"
        class_name = manifest.entry.split(":", 1)[-1] or "GeneratedComponent"
        module_content = self.MODULE_TEMPLATE.format(
            template_id=template.template_id,
            class_name=class_name,
            description=template.description or template.template_id,
        )
        artifacts.append(GeneratedArtifact(path=module_path, content=module_content, kind="module"))

        fragment = self.GRAPH_FRAGMENT_TEMPLATE.format(
            component_id=f"{template.template_id}.primary",
            component_type=manifest.kind.value,
            impl=manifest.entry,
            version=manifest.version,
        )
        fragment_path = root / "graphs" / f"{template.template_id}.fragment.xml"
        artifacts.append(
            GeneratedArtifact(path=fragment_path, content=fragment, kind="graph_fragment")
        )

        return artifacts

    def write_all(self, artifacts: list[GeneratedArtifact]) -> list[Path]:
        written: list[Path] = []
        for artifact in artifacts:
            artifact.path.parent.mkdir(parents=True, exist_ok=True)
            artifact.path.write_text(artifact.content)
            written.append(artifact.path)
        return written
