from __future__ import annotations

import hashlib
import json
from pathlib import Path

from metaharness.sdk.api import HarnessAPI
from metaharness.sdk.base import HarnessComponent
from metaharness.sdk.runtime import ComponentRuntime
from metaharness_ext.octave.capabilities import CAP_OCTAVE_SCRIPT_COMPILE
from metaharness_ext.octave.contracts import (
    OctaveEnvironmentReport,
    OctaveExecutionParams,
    OctaveExperimentSpec,
    OctaveOutputSpec,
    OctaveRunPlan,
)
from metaharness_ext.octave.slots import OCTAVE_SCRIPT_COMPILER_SLOT


class OctaveScriptCompilerComponent(HarnessComponent):
    async def activate(self, runtime: ComponentRuntime) -> None:
        self._runtime = runtime

    async def deactivate(self) -> None:
        self._runtime = None

    def declare_interface(self, api: HarnessAPI) -> None:
        api.bind_slot(OCTAVE_SCRIPT_COMPILER_SLOT)
        api.declare_input("task", "OctaveExperimentSpec")
        api.declare_input("environment", "OctaveEnvironmentReport", required=False)
        api.declare_output("plan", "OctaveRunPlan", mode="sync")
        api.provide_capability(CAP_OCTAVE_SCRIPT_COMPILE)

    def build_plan(
        self,
        spec: OctaveExperimentSpec,
        environment: OctaveEnvironmentReport | None = None,
    ) -> OctaveRunPlan:
        return self.compile(spec, environment)

    def compile(
        self,
        spec: OctaveExperimentSpec,
        environment: OctaveEnvironmentReport | None = None,
    ) -> OctaveRunPlan:
        if environment is not None and not environment.available:
            raise ValueError(f"Octave environment unavailable: {environment.status}")
        for package in spec.packages:
            if (
                environment is not None
                and package.required
                and package.name not in {package_fact.name for package_fact in environment.packages}
            ):
                raise ValueError(f"Required Octave package is unavailable: {package.name}")

        plan_id = self._build_plan_id(spec)
        run_id = f"run-{plan_id}"
        workspace_dir = (
            spec.workspace.working_directory
            if spec.workspace is not None and spec.workspace.working_directory
            else f".runs/octave/{spec.task_id}/{run_id}"
        )
        wrapper_source = self._render_wrapper(spec, plan_id)
        argv = [
            spec.executable.binary_name,
            "--no-gui",
            "--quiet",
            "--no-init-file",
            "mhe_wrapper.m",
        ]
        return OctaveRunPlan(
            plan_id=plan_id,
            task_id=spec.task_id,
            run_id=run_id,
            executable=spec.executable,
            wrapper_source=wrapper_source,
            workspace_dir=workspace_dir,
            input_assets=list(spec.inputs),
            expected_outputs=list(spec.expected_outputs),
            packages=list(spec.packages),
            execution_params=OctaveExecutionParams(
                argv=argv,
                workspace_dir=workspace_dir,
                timeout_seconds=spec.executable.timeout_seconds,
                output_directory=(
                    spec.workspace.output_directory if spec.workspace is not None else "outputs"
                ),
                environment=dict(spec.executable.env),
            ),
            graph_metadata=dict(spec.graph_metadata),
            promotion_metadata=dict(spec.promotion_metadata),
            evidence_refs=[f"octave://plan/{spec.task_id}/{plan_id}"],
        )

    def _build_plan_id(self, spec: OctaveExperimentSpec) -> str:
        payload = json.dumps(spec.model_dump(mode="json"), sort_keys=True)
        digest = hashlib.sha256(payload.encode()).hexdigest()[:12]
        return f"octave-{spec.task_id}-{digest}"

    def _render_wrapper(self, spec: OctaveExperimentSpec, plan_id: str) -> str:
        lines = [
            "% --- Auto-generated by metaharness_ext.octave ---",
            f"% Plan: {plan_id}  Task: {spec.task_id}",
            "more off;",
            "warning('on', 'all');",
            "try",
            "  addpath(pwd);",
            "  if exist('outputs', 'dir') ~= 7, mkdir('outputs'); endif;",
        ]
        for path in spec.script.add_paths:
            lines.append(f"  addpath({self._octave_string(path)});")
        for package in spec.packages:
            lines.append(f"  pkg load {package.name};")
        for asset in spec.inputs:
            target = asset.target_name or Path(asset.source_path).name
            if asset.kind == "mat":
                lines.append(f"  load({self._octave_string(target)});")
            elif asset.kind == "script":
                lines.append(f"  source({self._octave_string(target)});")
        for key, value in sorted(spec.parameters.items()):
            if isinstance(value, bool):
                rendered = "true" if value else "false"
            elif isinstance(value, int | float):
                rendered = repr(value)
            elif isinstance(value, str):
                rendered = self._octave_string(value)
            else:
                continue
            lines.append(f"  {key} = {rendered};")
        lines.extend(self._execution_lines(spec))
        lines.extend(self._expected_output_lines(spec.expected_outputs))
        lines.extend(
            [
                "  mhe_status = struct('status', 'completed', 'plan_id', "
                f"{self._octave_string(plan_id)}, 'task_id', {self._octave_string(spec.task_id)});",
                "  save('-text', 'mhe_status.txt', 'mhe_status');",
                "catch mhe_error",
                "  mhe_status = struct('status', 'failed', 'message', mhe_error.message);",
                "  save('-text', 'mhe_status.txt', 'mhe_status');",
                "  rethrow(mhe_error);",
                "end_try_catch",
                "",
            ]
        )
        return "\n".join(lines)

    def _execution_lines(self, spec: OctaveExperimentSpec) -> list[str]:
        script = spec.script
        if script.mode == "inline":
            return [
                f"  {line}" if line.strip() else "" for line in script.inline_source.splitlines()
            ]
        if script.mode == "file":
            return [f"  source({self._octave_string(script.script_path or '')});"]
        args = ", ".join(script.function_args)
        return [f"  {script.function_name}({args});"]

    def _expected_output_lines(self, outputs: list[OctaveOutputSpec]) -> list[str]:
        lines: list[str] = []
        for output in outputs:
            variable = output.variable_name or output.name
            if output.kind == "variable":
                lines.append(f"  if exist({self._octave_string(variable)}, 'var') ~= 1")
                lines.append(
                    f"    error('mhe:missing_output', {self._octave_string(variable + ' not defined')});"
                )
                lines.append("  endif;")
                file_name = output.file_name or f"outputs/{variable}.txt"
                lines.append(
                    f"  save('-text', {self._octave_string(file_name)}, {self._octave_string(variable)});"
                )
            elif output.kind == "mat":
                lines.append(
                    f"  save('-mat', {self._octave_string(output.file_name or '')}, "
                    f"{self._octave_string(variable)});"
                )
            elif output.kind == "json":
                lines.append("  if exist('jsonencode', 'builtin') || exist('jsonencode', 'file')")
                lines.append(
                    f"    fid = fopen({self._octave_string(output.file_name or '')}, 'w');"
                )
                lines.append(
                    f"    fputs(fid, jsonencode(struct({self._octave_string(variable)}, {variable}))); "
                )
                lines.append("    fclose(fid);")
                lines.append("  endif;")
        return lines

    def _octave_string(self, value: str) -> str:
        escaped = value.replace("'", "''")
        return f"'{escaped}'"
