from __future__ import annotations

import hashlib
from pathlib import Path

from metaharness_ext.boutpp.contracts import BoutPPOptionValue, BoutPPProblemSpec, BoutPPRunPlan


class BoutPPCompilerComponent:
    def compile(self, spec: BoutPPProblemSpec, run_id: str, workspace_dir: str) -> BoutPPRunPlan:
        plan_id = self._build_plan_id(spec)
        data_dir = str(Path(workspace_dir) / spec.output.data_dir)
        command = self._build_command(spec, data_dir)
        return BoutPPRunPlan(
            plan_id=plan_id,
            task_id=spec.task_id,
            run_id=run_id,
            spec=spec,
            workspace_dir=str(workspace_dir),
            data_dir=data_dir,
            bout_inp_content=self.render_bout_inp(spec),
            command=command,
            expected_settings_path=str(Path(data_dir) / spec.output.settings_file),
            expected_log_glob=str(Path(data_dir) / spec.output.log_glob),
            expected_dump_glob=str(Path(data_dir) / spec.output.dump_glob),
            expected_restart_glob=str(Path(data_dir) / spec.output.restart_glob),
            graph_metadata=spec.graph_metadata,
            promotion_metadata=spec.promotion_metadata,
            evidence_refs=list(spec.evidence_refs),
        )

    @staticmethod
    def _build_plan_id(spec: BoutPPProblemSpec) -> str:
        payload = spec.model_dump_json(exclude={"graph_metadata", "promotion_metadata", "evidence_refs"})
        return hashlib.sha256(payload.encode()).hexdigest()[:16]

    def render_bout_inp(self, spec: BoutPPProblemSpec) -> str:
        lines = ["# Auto-generated by MHE BOUT++ compiler"]
        for key in sorted(spec.top_level_options):
            lines.append(f"{key} = {self._format_value(spec.top_level_options[key])}")
        for section in sorted(spec.options):
            lines.append("")
            lines.append(f"[{section}]")
            values = spec.options[section]
            for key in sorted(values):
                lines.append(f"{key} = {self._format_value(values[key])}")
        lines.append("")
        return "\n".join(lines)

    def _build_command(self, spec: BoutPPProblemSpec, data_dir: str) -> list[str]:
        command: list[str] = []
        if spec.mpi.launcher_mode == "mpi":
            command.extend([spec.mpi.launcher, "-np", str(spec.mpi.processes), *spec.mpi.extra_args])
        command.append(spec.executable)
        command.extend(spec.restart.argv_tokens)
        command.extend(["-d", data_dir])
        command.extend(spec.cli_overrides)
        return command

    @staticmethod
    def _format_value(value: BoutPPOptionValue) -> str:
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, str):
            if value.startswith('"') and value.endswith('"'):
                return value
            if any(char.isspace() for char in value) and not any(op in value for op in "+-*/^&|!<>(){}[]"):
                return f'"{value}"'
            return value
        return str(value)
